### ISSUE TITLE
css network training data

### ISSUE THREAD

**Issue by slinghe0321** [TRI-ML/sdflabel#4]
Hi, could you provide the whole dataset(8k patches image_rgb and image_uvw) for css network training? There are only 5 examples in the 'data/db/crops'. Thanks a lot.

**Comment by zakharos** [comment]
Hi there!
Unfortunately we are not able to release the training dataset since it was generated from a proprietary dataset provided by [Parallel Domain](https://paralleldomain.com/). A possible alternative would be to use [CARLA](https://carla.org/) to extract patches and poses from there. Then using the respective car models and poses, one car render NOCS (e.g. using [nocs-renderer](https://github.com/zakharos/nocs-renderer)).

**Comment by Tariq-Abuhashim** [comment]
Hi Sergey;
How do you generate a json file similar to crops.json that you have in the repository for training.
More specifically, starting from CARLA and your nocs-renderer, how to populate:
latent
intrinsics
scale
in the json file?

The nocs images generated by nocs-renderer look like grayscale images, while sdflabel takes colored nocs images, how to generate those?
