### ISSUE TITLE
Rendering backface of the discs

### ISSUE THREAD

**Issue by magistri** [TRI-ML/sdflabel#6]
Hi, 
thanks for sharing the implementation. I have a short question. 

Are discs rendered on both sides or are they rendered only when looking at their top face? (like in common mesh visualization)

**Comment by zakharos** [comment]
Hi @magistri,
I apologize for the delay! In our implementation you can filter points using [back-face culling](https://github.com/TRI-ML/sdflabel/blob/416c27dbcc6a341c3038783beb46d3f8eccb8177/sdfrenderer/renderer/projection.py#L117) since we analytically compute normals by computing a derivative of SDF with respect to input point locations. Alternatively, you can use an [HPR operator](https://github.com/TRI-ML/sdflabel/blob/416c27dbcc6a341c3038783beb46d3f8eccb8177/sdfrenderer/renderer/projection.py#L118) as described in [here](http://www.weizmann.ac.il/math/ronen/sites/math.ronen/files/uploads/katz_tal_basri_-_direct_visibility_of_point_sets.pdf). If both options are disabled, you'll be rendering discs on both sides.
